name: recsys_autoencoders
channels:
  - defaults
dependencies:
  - python=3.6
  - cloudpickle=0.6.1
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - seaborn=0.9
  - click=6.7
  - keras=2.1.5
  - tensorflow==1.7.0  
  - scipy=1.0.1
  - graphviz
  - pydotplus
  - pip:
    - mlflow
